#source 'https://rubygems.org'
source 'http://ruby.taobao.org'

gem 'rails', '3.2.14'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

# template engine
# using Slim template for Backbone
gem 'temple','0.4.0'
gem 'tilt', '~> 1.3'
gem 'skim', '0.8.4'
gem 'slim', '1.2.1'
gem 'slim-rails'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
	gem 'compass-rails', '1.0.3'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
 	gem 'libv8', '~> 3.11.8'
  gem 'therubyracer', :platforms => :ruby
  gem 'turbo-sprockets-rails3', '0.3.6'
  gem 'uglifier', '1.2.7'
end

# uploading component
#gem 'carrierwave', '0.7.1'
#gem 'mini_magick', '3.3', :require => false
#gem 'rmagick'
#gem 'carrierwave-mongoid','0.1.0', :require => 'carrierwave/mongoid'

gem 'mongoid', '3.1.3'
gem 'mongoid_auto_increment_id', '0.5.1'
gem 'mongoid_rails_migrations', '1.0.0'
#gem 'mysql2'

# user management
gem 'devise'
#gem 'omniauth'
#gem 'omniauth-weibo-oauth2'
#gem 'weibo_2'

# permission
gem 'cancan', '~> 1.6.8'

gem 'inherited_resources'

# pagination
gem 'will_paginate', '3.0.3'

group :development do
  gem 'quiet_assets', '~> 1.0.1'
  gem 'awesome_print'
  gem 'rb-fsevent', '~> 0.9.3'  
end

group :development, :test do
  gem 'jazz_hands'
  gem 'capistrano', '2.12.0', :require => false
  gem 'rvm-capistrano', '1.2.6', :require => false
  gem 'thin'
  gem 'hirb'
  gem 'simplecov', :require => false
  gem 'mongoid_colored_logger', :git => 'https://github.com/huacnlee/mongoid_colored_logger.git'
  gem 'newrelic_rpm'

	gem "rspec"
	gem "rspec-mocks"
  gem 'rspec-rails', '2.11.0'
	gem "rspec-cells"
  gem 'factory_girl_rails'
  gem 'spork'
  gem 'autotest-standalone'
  gem 'autotest-fsevent'
  gem 'autotest-growl'
end

group :test do
  gem "faker", "~> 1.1.2"
  gem "capybara", "~> 2.1.0"
  gem "database_cleaner", "~> 1.0.1"
  gem "launchy", "~> 2.3.0"
  gem "shoulda-matchers", "~> 2.2.0"
  gem "selenium-webdriver", "~> 2.35.1"
end

#gem "twitter-bootstrap-rails", :git => 'https://github.com/seyhunak/twitter-bootstrap-rails.git'
gem 'unicorn'
#gem 'unicorn-worker-killer'

gem 'simple_form'
gem 'jquery-rails'

# for memcached
gem "dalli"

#gem "mobile-fu", "~> 1.2.1"

#gem 'whenever', :require => false


